version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header:
    $ref: "#/messages/template.header"
  icon: icon.png
  required:
    - build
    - repo
  info:
    git url: >-
      [{{repository}}]({{repository}})
    git branch: >-
      [{{branch}}]({{repository}}/tree/{{branch}})
toolchain:
  name: '{{baseName}}-toolchain'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: '{{baseName}}'
      repo_url: '{{repository}}'
      type: clone
      has_issues: false
      enable_traceability: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          SAMPLE_REPO: repo
          BIND_TO: '{{serviceId}}'
          BRANCH: 'master'
          CF_APP_NAME: '{{form.pipeline.parameters.prod-app-name}}'
          PROD_SPACE_NAME: '{{form.pipeline.parameters.prod-space}}'
          PROD_ORG_NAME: '{{form.pipeline.parameters.prod-organization}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
        execute: true
form:
  pipeline:
    parameters:
      prod-app-name: '{{appName}}'
      prod-region: "{{region}}"
      prod-organization: "{{org}}"
      prod-space: "{{space}}"
    schema:
      $ref: deploy.json
